spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tsglxt
    username: root
    password: ADMIN
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml